export enum EnumScopes {
  ADM_PLACES = 'DEVSEEDER/PLACES/API/ADM',
  GET_ALL = 'DEVSEEDER/PLACES/API/GET_ALL',
  SEED_ALL = 'DEVSEEDER/PLACES/APi/SEED_ALL',
  GET_SEED_REGIONS = 'DEVSEEDER/PLACES/API/GET_SEED_REGIONS',
  RESOLUTION = 'DEVSEEDER/PLACES/API/RESOLUTION'
}
