repository:
  neighborhoods:
    guia-mais:
      url: 'https://www.guiamais.com.br/bairros'
database:
  mongodb:
    connection: 'mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL_CONNECTION}${MONGODB_DATABASE_NAME}${MONGODB_SUFIX_PARAMS}'
microservices:
  rabbitmq:
    url: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}/${RABBITMQ_VHOST}'
    queue:
      events: 'seed-events'
      publishes: 'seed-messages'
    exchange:
      seed:
        neighborhoods:
          by:
            city:
              success: 'seed-by-city-success'
              error: 'seed-by-city-error'
    event:
      seed:
        neighborhoods:
          by:
            city: 'seed-by-city'

api:
  port: 3000
doc:
  version: 0.0.5
