repository:
  neighborhoods:
    guia-mais:
      url: 'https://www.guiamais.com.br/bairros'
database:
  mongodb:
    connection: 'mongodb+srv://dev-seeder-root:hpYpxyjrKExNQviu@devseeder.v6xtv.mongodb.net/places?retryWrites=true&w=majority&ssl=true&wtimeoutMS=0'
api:
  port: 3000
doc:
  version: 0.0.5
