repository:
  neighborhoods:
    guia-mais:
      url: 'https://www.guiamais.com.br/bairros'
database:
  mongodb:
    connection: 'mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL_CONNECTION}${MONGODB_DATABASE_NAME}${MONGODB_SUFIX_PARAMS}'
api:
  port: 3000
doc:
  version: 0.0.5
