repository:
  neighborhoods:
    guia-mais:
      url: 'https://www.guiamais.com.br/bairros'
database:
  mongodb:
    connection: 'mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL_CONNECTION}${MONGODB_DATABASE_NAME}${MONGODB_SUFIX_PARAMS}'
microservices:
  rabbitmq:
    url: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}/${RABBITMQ_VHOST}'
    queue:
      seed:
        neighborhoods:
          process: 'seed-by-city'
          success: 'seed-by-city'
          error: 'seed-by-error'

api:
  port: 3000
doc:
  version: 0.0.5
